#!/bin/bash
# ==============================================================
# GOLDY-LUX UPDATE SCRIPT
# ==============================================================
# Regenerates all analysis, updates predictions, refreshes README.
#
# Usage:
#   ./update_gold.sh              # Full update
#   ./update_gold.sh --quick      # Skip Monte Carlo (faster)
#   ./update_gold.sh --push       # Auto-commit and push to git
#
# Requirements: python3, pip packages (yfinance, plotly, kaleido, numpy, pandas)
# ==============================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

QUICK=false
PUSH=false

for arg in "$@"; do
    case $arg in
        --quick) QUICK=true ;;
        --push)  PUSH=true ;;
    esac
done

echo "==========================================="
echo " GOLDY-LUX UPDATE"
echo " $(date '+%Y-%m-%d %H:%M:%S')"
echo "==========================================="
echo ""

# Ensure directories exist
mkdir -p output docs data

# Step 1: Scenario Tree Analysis
echo "[1/4] Running scenario tree analysis..."
python3 src/scenario_tree.py
echo ""

# Step 2: Monte Carlo Simulation
if [ "$QUICK" = false ]; then
    echo "[2/4] Running Monte Carlo simulation (50k paths)..."
    python3 src/monte_carlo.py
    echo ""
else
    echo "[2/4] Monte Carlo skipped (--quick mode)"
    echo ""
fi

# Step 3: Track Predictions
echo "[3/4] Tracking predictions..."
python3 src/prediction_tracker.py
echo ""

# Step 4: Update README bottom line
echo "[4/4] Updating README..."
python3 src/generate_readme_section.py
echo ""

# Copy HTML outputs to docs/ for GitHub Pages
cp output/*.html docs/ 2>/dev/null || true
echo "  Copied HTML to docs/ for GitHub Pages"

echo ""
echo "==========================================="
echo " UPDATE COMPLETE"
echo "==========================================="
echo ""
echo " Output files:  output/"
echo " Interactive:   open output/scenario_tree.html"
echo "                open output/mc_simulated_paths.html"
echo " GitHub Pages:  docs/"
echo ""

# Optional: commit and push
if [ "$PUSH" = true ]; then
    echo "Committing and pushing..."
    git add -A
    git commit -m "$(cat <<EOF
Update goldy-lux analysis $(date '+%Y-%m-%d')

Auto-generated by update_gold.sh
EOF
)"
    git push
    echo "Pushed to remote."
fi
